### ISSUE TITLE
Support rest parameters & default values

### ISSUE THREAD

**Issue by GlaDos28** [sindresorhus/fn-args#7]
"fn-args": "^2.0.0",

Two bugs in one issue:

1. Rest parameter. Just try this:

const fnArgs = require("fn-args");

console.log(fnArgs((...arg1) => {})); // => []
console.log(fnArgs((arg1, ...arg2) => {})); // => [ 'arg1', '...arg2' ]

This is wrong as minimum because of ambiguity of rest parameter presence.

2. The reason I referred to Your package (my small internal argument getter works to this moment) is to skip default values:

console.log(fnArgs((arg1 = 2) => {})); // => []
console.log(fnArgs((arg1, arg2 = 2) => {})); // => [ 'arg1', 'arg2 = 2' ]
console.log(fnArgs((arg1 = 2, arg2) => {})); // => []

Of course, this is not what we expect, really?

Yeah, this is hell - to get rid of default values. But if You want to (I hope) remove this bug, try not to parse all 'default value code', but follow the number of open/close (, ), {, } and skip to the comma or parenthesis when no parenthesis depth occurs. Nevertheless, the code will be complicated dramatically.

**Comment by sindresorhus** [comment]
Yeah, those didn't really exist when I first made this module. Pull request welcome :)

**Comment by GlaDos28** [comment]
Sent a pull request. Sorry for revert, I saw it only now - just a folly, I think it is not critical.
